export const MAX_PROJECT_NAME_LENGTH = 40;
export const MAX_PROJECT_DESCRIPTION_LENGTH = 220;
export const MAX_TASK_TITLE_LENGTH = 60;
export const MAX_TASK_DESCRIPTION_LENGTH = 220;
export const MAX_USERNAME_LENGTH = 20;
